apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-config
data:
  nginx.conf: |
    events {}
    http {
      server {
          listen 80;
          location / {
              proxy_pass http://localhost:3000;
              proxy_set_header Host $host;
              proxy_set_header X-Real-IP $remote_addr;
              proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
              proxy_set_header X-Forwarded-Proto $scheme;
          }
      }
    }

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: last-week-project-deployment
spec:
  replicas: 10
  selector:
    matchLabels:
      app: last-week-project
  template:
    metadata:
      labels:
        app: last-week-project
    spec:
      containers:
      - name: redis
        image: redis
        resources:
          requests:
            cpu: "100m"
            memory: "256Mi"
          limits:
            cpu: "100m"
            memory: "256Mi"
      - name: app-container
        image: teamspartacontents/k8s_lecture1:last-week-project
        env:
        - name: DB_HOST
          valueFrom:
            secretKeyRef:
              name: mini-project-secret
              key: DB_HOST
        - name: DB_USER
          valueFrom:
            secretKeyRef:
              name: mini-project-secret
              key: DB_USER
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mini-project-secret
              key: DB_PASS
        - name: DB_DATABASE
          valueFrom:
            secretKeyRef:
              name: mini-project-secret
              key: DB_DATABASE
        resources:
          requests:
            cpu: "500m"
            memory: "500Mi"
          limits:
            cpu: "500m"
            memory: "500Mi"
        ports:
        - containerPort: 3000
      - name: nginx
        image: nginx:latest
        resources:
          requests:
            cpu: "100m"
            memory: "100Mi"
          limits:
            cpu: "100m"
            memory: "100Mi"
        ports:
        - containerPort: 80
        volumeMounts:
        - name: nginx-config
          mountPath: /etc/nginx/nginx.conf
          subPath: nginx.conf
      volumes:
      - name: nginx-config
        configMap:
          name: nginx-config

---
apiVersion: v1
kind: Service
metadata:
  name: last-week-project-svc
  namespace: default
spec:
  selector:
    app: last-week-project
  ports:
    - port: 80
      targetPort: 80

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: last-week-project-ingress
  namespace: default
  annotations:
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/target-type: ip
spec:
  # ingressClassName: alb   # AWS 설정
  rules:
    - http:
        paths:
        - path: /
          pathType: Prefix
          backend:
            service:
              name: last-week-project-svc
              port:
                number: 80