apiVersion: v1
kind: Secret
metadata:
  name: mini-project-secret
  namespace: default
data:
  DB_HOST: bXlzcWwtMC5teXNxbC5kZWZhdWx0LnN2Yy5jbHVzdGVyLmxvY2Fs
  DB_USER: cm9vdA==
  DB_PASS: c3BhcnRh
  DB_DATABASE: c3BhcnRh