apiVersion: v1
kind: Pod
metadata:
  name: practice-pod
  namespace: second-week
spec: 
  containers: 
  - name: nginx
    image: asia-northeast3-docker.pkg.dev/ornate-axiom-452414-s4/kube-study-registry/second-week-exercise:1.0.0
    env:
    - name: TITLE
      valueFrom:
        configMapKeyRef:
          name: configmap
          key: PUBLIC_NAME
    - name: PASSWORD
      valueFrom:
        secretKeyRef:
          name: secret
          key: SECRET_NAME
    ports: 
    - containerPort: 3000
    